//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendsTable
    {
        public int ftable_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<long> friend_id { get; set; }
        public Nullable<int> groupNo { get; set; }
        public Nullable<bool> Isaccepted { get; set; }
    
        public virtual register register { get; set; }
        public virtual register register1 { get; set; }
    }
}
