//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_key
    {
        public int groupKeyId { get; set; }
        public Nullable<long> userId { get; set; }
        public string groupKey { get; set; }
        public Nullable<int> groupNo { get; set; }
    
        public virtual register register { get; set; }
        public virtual group group { get; set; }
    }
}
