//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MlaDatabaseEntities1 : DbContext
    {
        public MlaDatabaseEntities1()
            : base("name=MlaDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<friendsTable> friendsTables { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<group_key> group_key { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<student> students { get; set; }
    }
}
