//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int postId { get; set; }
        public string postText { get; set; }
        public Nullable<int> postType { get; set; }
        public Nullable<int> groupNo { get; set; }
        public byte[] timeStamp { get; set; }
        public string digitalSignature { get; set; }
        public Nullable<long> ownerId { get; set; }
        public string sessionKey { get; set; }
        public Nullable<int> originalPostId { get; set; }
    
        public virtual group group { get; set; }
        public virtual register register { get; set; }
    }
}
